services:
  - type: web
    name: django-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn your_project.wsgi:application --bind 0.0.0.0:10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-django-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
